Repository wonderflow-bv/wanda, pull requests merged in 2022-05, with the labels that each got.

#153 style: standardize chip padding
  .changeset/weak-dogs-brake.md
  packages/react-components/src/components/chip/chip.module.css
Labels: on hold

#156 155 table should have preselected rows
  .changeset/many-grapes-roll.md
  apps/docs/pages/components/layouts/table.mdx
  packages/react-components/src/components/table/table.stories.tsx
  packages/react-components/src/components/table/table.tsx
Labels: invalid, feature

#160 fix(table): fixed subRows checkbox selection
  packages/react-components/src/components/table/table.tsx
Labels: bug
